// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskTracker.Infrastructure.Persistence;

#nullable disable

namespace TaskTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WebAPIDbContext))]
    partial class WebAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskTracker.Domain.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("taskid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime?>("TaskCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskcompletedatutc");

                    b.Property<DateTime>("TaskCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskcreatedatutc");

                    b.Property<DateTime?>("TaskDeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskdeletedatutc");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("text")
                        .HasColumnName("taskdescription");

                    b.Property<DateTime?>("TaskDueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskdueatutc");

                    b.Property<DateTime?>("TaskEndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskendatutc");

                    b.Property<int>("TaskGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("taskgroupid");

                    b.Property<short>("TaskPriority")
                        .HasColumnType("smallint")
                        .HasColumnName("taskpriority");

                    b.Property<int?>("TaskProgress")
                        .HasColumnType("integer")
                        .HasColumnName("taskprogress");

                    b.Property<int>("TaskSortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("tasksortorder");

                    b.Property<DateTime?>("TaskStartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskstartatutc");

                    b.Property<DateTime>("TaskUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskupdatedatutc");

                    b.HasKey("TaskId");

                    b.HasIndex("TaskGroupId");

                    b.ToTable("tasks", "public");
                });

            modelBuilder.Entity("TaskTracker.Domain.Models.TaskDependency", b =>
                {
                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("DependsOnTaskId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TaskId", "DependsOnTaskId");

                    b.HasIndex("DependsOnTaskId");

                    b.ToTable("taskdependencies", "public", t =>
                        {
                            t.HasCheckConstraint("chk_no_self_dependency", "\"TaskId\" <> \"DependsOnTaskId\"");
                        });
                });

            modelBuilder.Entity("TaskTracker.Domain.Models.TaskGroup", b =>
                {
                    b.Property<int>("TaskGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("taskgroupid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskGroupId"));

                    b.Property<DateTime?>("TaskGroupArchivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskgrouparchivedatutc");

                    b.Property<string>("TaskGroupColor")
                        .HasColumnType("text")
                        .HasColumnName("taskgroupcolor");

                    b.Property<DateTime>("TaskGroupCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskgroupcreatedatutc");

                    b.Property<string>("TaskGroupDescription")
                        .HasColumnType("text")
                        .HasColumnName("taskgroupdescription");

                    b.Property<int>("TaskGroupSortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("taskgroupsortorder");

                    b.Property<DateTime>("TaskGroupUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taskgroupupdatedatutc");

                    b.HasKey("TaskGroupId");

                    b.ToTable("taskgroups", "public");
                });

            modelBuilder.Entity("TaskTracker.Domain.Models.Task", b =>
                {
                    b.HasOne("TaskTracker.Domain.Models.TaskGroup", "TaskGroup")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskGroup");
                });

            modelBuilder.Entity("TaskTracker.Domain.Models.TaskDependency", b =>
                {
                    b.HasOne("TaskTracker.Domain.Models.Task", "DependsOnTask")
                        .WithMany("DependentOnMe")
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTracker.Domain.Models.Task", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskTracker.Domain.Models.Task", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("DependentOnMe");
                });

            modelBuilder.Entity("TaskTracker.Domain.Models.TaskGroup", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
